# Generated by Django 5.2.6 on 2025-10-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('jn', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pteam', models.CharField(max_length=50)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('date_of_creation', models.DateTimeField()),
            ],
        ),
    ]
