# Generated by Django 5.2.6 on 2025-10-08 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0002_alter_player_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
