# Generated by Django 5.2.6 on 2025-10-08 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0003_alter_player_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 13, 33, 14, 345240, tzinfo=datetime.timezone.utc)),
        ),
    ]
