# Generated by Django 5.2.6 on 2025-10-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0004_alter_player_date_of_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_creation',
        ),
    ]
